### PR TITLE
Port to Owens

### PR DESCRIPTION
**Pull request by brianmcmichael**
Modified configuration to run on Owens cluster.

Tested all configurations.

### CODE REVIEW

**Comment by nickjer** [comment]
Please open a task up in Asana for this so we can better track this through the software deployment lifecycle. Also, are all versions of Abaqus listed in the form supported by Owens?

**Comment by brianmcmichael** [comment]
https://app.asana.com/0/425364008343147/475427362403540

**Comment by brianmcmichael** [comment]
Tested all configurations.

**Comment by nickjer** [comment]
You should make individual tasks for each app as their deployment lifecycles are separate.

So for each app you will have an Asana task with the following subtasks:

- [ ] update code
- [ ] review code
- [ ] deploy to webdev02/04
- [ ] test it on webdev02/04
- [ ] release/tag code
- [ ] deploy to webtest02/04
- [ ] test it on webtest02/04
- [ ] deploy to web02/04

This helps the release engineer to know what needs to go out and he/she can check off each app that was deployed.

**Pull request merged**
